module.exports = {
  docs: [
    {
      type: 'doc',
      id: 'background/background',
    },
    {
      type: 'category',
      label: '开始',
      collapsed: false,
      items: ['start/install', 'start/dripform', 'start/schema'],
    },
    {
      type: 'category',
      label: 'API',
      collapsed: false,
      items: [
        'use/unitedSchema',
        'use/uiComponents',
        'use/customComponents',
        'use/control',
        'use/onValidate',
        'use/onQuery',
        'use/customFunc',
        'use/formData',
        'use/parse',
        'use/transform',
      ],
    },
    {
      type: 'category',
      label: '组件',
      collapsed: true,
      items: [
        // 'components/cascaderField',
        'components/checkboxField',
        'components/colorPickerField',
        'components/datePickerField',
        'components/nullField',
        'components/numberField',
        'components/radioField',
        'components/selectField',
        'components/sliderField',
        'components/switchField',
        'components/textField',
        'components/timePickerField',
        // 'components/treeSelectField',
        'components/uploaderField',
        'components/objectContainer',
        'components/arrayContainer',
      ],
    },
    {
      type: 'category',
      label: '进阶',
      collapsed: true,
      items: [
        'expert/formdata',
        'expert/multiForm',
        'expert/customTheme',
        'expert/customVerify',
        'expert/getset',
        'expert/automatic',
      ],
    },
  ],
  generator: [
    {
      type: 'doc',
      id: 'generator/start/generator',
    },
    {
      type: 'doc',
      id: 'generator/start/use',
    },
    {
      type: 'category',
      label: 'props',
      collapsed: true,
      items: [
        'generator/props/schema',
        'generator/props/theme',
        'generator/props/components',
        'generator/props/options',
        'generator/props/customComponents',
      ],
    },
  ],
}
