module.exports = {
  docs: [
    {
      type: 'doc',
      id: 'form/introduction/introduction',
    },
    {
      type: 'doc',
      id: 'form/quickStart/quickStart',
    },
    {
      type: 'category',
      label: 'unitedSchema协议',
      link: {
        type: 'doc',
        id: 'form/unitedSchema/unitedSchema',
      },
      collapsed: false,
      items: [
        'form/unitedSchema/dataType',
        'form/unitedSchema/uiType',
        'form/unitedSchema/schemaKeyword',
      ],
    },
    {
      type: 'category',
      label: '用法',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: '用法',
        description: '了解drip form如何使用',
        slug: '/form/use',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
      items: [
        'form/use/customComponent',
        'form/use/theme',
        {
          type: 'category',
          label: '校验',
          collapsed: false,
          link: {
            type: 'doc',
            id: 'form/use/validate/validate',
          },
          items: [
            'form/use/validate/jsonSchemaValidate',
            'form/use/validate/asyncValidate',
            'form/use/validate/customValidate',
          ],
        },
        {
          type: 'category',
          label: '联动配置',
          collapsed: false,
          link: {
            type: 'generated-index',
            title: '联动配置',
            description: '了解drip form如何配置常见的联动效果',
            slug: '/form/use/control',
            keywords: ['guides'],
            image: '/img/docusaurus.png',
          },
          items: [
            'form/use/control/vcontrol',
            'form/use/control/globalChange',
            'form/use/control/onChange',
            'form/use/control/other',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '进阶指南',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: '进阶指南',
        description: '更深入了解drip form',
        slug: '/form/advanced',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
      items: [
        'form/advanced/customTheme',
        'form/advanced/customKeyword',
        'form/advanced/customValidatePlugin',
        {
          type: 'category',
          label: '其他内部结构',
          collapsed: false,
          link: {
            type: 'generated-index',
            title: '其他内部结构',
            description: '深入了解drip form内部运行机制',
            slug: '/form/advanced/otherInternal',
            keywords: ['guides'],
            image: '/img/docusaurus.png',
          },
          items: [
            'form/advanced/otherInternal/default',
            'form/advanced/otherInternal/required',
            'form/advanced/otherInternal/errType',
            'form/advanced/otherInternal/customAjv',
            'form/advanced/otherInternal/supportJsonSchema',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'API参考',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'API参考',
        description: '了解Drip form 内部的API',
        slug: '/form/API',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
      items: [
        {
          type: 'category',
          label: 'drip form props',
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Drip form 参数',
            description: '了解Drip form 支持传递哪些参数',
            slug: '/form/API/formProp',
            keywords: ['guides'],
            image: '/img/docusaurus.png',
          },
          items: [
            'form/API/formProp/unitedSchema',
            'form/API/formProp/uiComponents',
            'form/API/formProp/formData',
            'form/API/formProp/customComponents',
            'form/API/formProp/ref',
            'form/API/formProp/globalData',
            'form/API/formProp/control',
            'form/API/formProp/parse',
            'form/API/formProp/transform',
            'form/API/formProp/onValidate',
            'form/API/formProp/onQuery',
            'form/API/formProp/onEvent',
            'form/API/formProp/onMount',
            'form/API/formProp/onSubmit',
            'form/API/formProp/onCancel',
            'form/API/formProp/plugins',
            'form/API/formProp/options',
            'form/API/formProp/fetchApi',
            'form/API/formProp/customFunc',
            'form/API/formProp/containerHoc',
            'form/API/formProp/ajvOptions',
          ],
        },
        {
          type: 'category',
          label: 'utils',
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'utils',
            description: '了解Drip form 内部的一些通用方法',
            slug: '/form/API/utils',
            keywords: ['guides'],
            image: '/img/docusaurus.png',
          },
          items: [
            'form/API/utils/get',
            'form/API/utils/set',
            'form/API/utils/merge',
            'form/API/utils/getKey',
            'form/API/utils/dispatch',
          ],
        },
        {
          type: 'category',
          label: 'hooks',
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'hooks',
            description: '了解Drip form 内部的一些通用hooks',
            slug: '/form/API/hooks',
            keywords: ['guides'],
            image: '/img/docusaurus.png',
          },
          items: ['form/API/hooks/useField', 'form/API/hooks/useQuery'],
        },
      ],
    },
    {
      type: 'link',
      label: '贡献',
      href: 'https://github.com/JDFED/drip-form/blob/dev/CONTRIBUTING.md',
    },
  ],
  generator: [
    {
      type: 'doc',
      id: 'generator/start/generator',
    },
    {
      type: 'doc',
      id: 'generator/start/use',
    },
    {
      type: 'category',
      label: 'props',
      collapsed: false,
      items: [
        'generator/props/schema',
        'generator/props/theme',
        'generator/props/components',
        'generator/props/options',
        'generator/props/customComponents',
      ],
    },
  ],
}
